const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path');
const file=path.join(__dirname,'../../../tools/organizer/core.cjs'); const api=fs.existsSync(file)?require(file):{};
test('first usable chapter behavior',t=>{ assert.equal(typeof api.planDirectory,'function'); const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sort-')); t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); fs.writeFileSync(path.join(dir,'a.txt'),'A'); const p=api.planDirectory(dir); assert.equal(p.items[0].target,'documents/a.txt'); const r=api.applyPlan(p); assert.equal(r.completed.length,1); assert.equal(fs.readFileSync(path.join(dir,'documents/a.txt'),'utf8'),'A'); assert.equal(fs.existsSync(path.join(dir,'a.txt')),false); });

test('collision preflight keeps every original',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sort-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'a.txt'),'A');fs.writeFileSync(path.join(dir,'b.txt'),'B');fs.mkdirSync(path.join(dir,'documents'));fs.writeFileSync(path.join(dir,'documents/b.txt'),'old');assert.throws(()=>api.planDirectory(dir),/COLLISION/);assert.equal(fs.readFileSync(path.join(dir,'a.txt'),'utf8'),'A');});
test('stale plan and symlink destination rejected',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sort-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'a.txt'),'A');const p=api.planDirectory(dir);fs.writeFileSync(path.join(dir,'a.txt'),'changed');assert.throws(()=>api.applyPlan(p),/CHANGED/);});

test('staging preserves selected originals',t=>{assert.equal(typeof api.stageDirectory,'function');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'stage-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const src=path.join(dir,'source');const dest=path.join(dir,'work');fs.mkdirSync(src);fs.writeFileSync(path.join(src,'a.txt'),'original');api.stageDirectory(src,dest);api.applyPlan(api.planDirectory(dest));assert.equal(fs.readFileSync(path.join(src,'a.txt'),'utf8'),'original');assert.equal(fs.readFileSync(path.join(dest,'documents/a.txt'),'utf8'),'original');});

test('symlink destination is refused without changing source',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sort-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const root=path.join(dir,'work');const other=path.join(dir,'outside');fs.mkdirSync(root);fs.mkdirSync(other);fs.writeFileSync(path.join(root,'a.txt'),'A');try{fs.symlinkSync(other,path.join(root,'documents'),'junction');}catch(e){if(e.code==='EPERM'){t.skip('Creating links requires OS privilege');return;}throw e;}assert.throws(()=>api.planDirectory(root),/INVALID/);assert.equal(fs.readdirSync(other).length,0);});
test('destination created after preview stops preflight',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sort-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'a.txt'),'A');const p=api.planDirectory(dir);fs.mkdirSync(path.join(dir,'documents'));fs.writeFileSync(path.join(dir,'documents/a.txt'),'other');assert.throws(()=>api.applyPlan(p),/COLLISION/);assert.equal(fs.readFileSync(path.join(dir,'a.txt'),'utf8'),'A');});
