const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path');
const file=path.join(__dirname,'../../../tools/notes/core.cjs'); const api=fs.existsSync(file)?require(file):{};
test('first usable chapter behavior',t=>{ assert.equal(typeof api.previewBlocks,'function'); assert.deepEqual(api.previewBlocks('# 標題\n<script>alert(1)</script>'),[{tag:'h1',text:'標題'},{tag:'p',text:'<script>alert(1)</script>'}]); });

test('cancel open and save retain dirty text',async()=>{assert.equal(typeof api.createNoteSession,'function');const s=api.createNoteSession();s.edit('unsaved');const d={askDirty:async()=> 'save',chooseSave:async()=>null,chooseOpen:async()=>null};assert.equal((await s.open(d)).canceled,true);assert.equal(s.snapshot().text,'unsaved');assert.equal(s.snapshot().dirty,true);assert.equal(await s.canLeave(d),false);});
test('save then reopen and detect external changes',async t=>{assert.equal(typeof api.createNoteSession,'function');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'note-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'a.md');const s=api.createNoteSession();s.edit('# hello');await s.save({chooseSave:async()=>file});assert.equal(s.snapshot().dirty,false);fs.writeFileSync(file,'external');s.edit('new');await assert.rejects(s.save({}),/CHANGED/);assert.equal(fs.readFileSync(file,'utf8'),'external');});

test('dirty discard followed by picker cancel keeps original session',async()=>{const s=api.createNoteSession();s.edit('keep');const r=await s.open({askDirty:async()=> 'discard',chooseOpen:async()=>null});assert.equal(r.canceled,true);assert.equal(s.snapshot().text,'keep');assert.equal(s.snapshot().dirty,true);});
test('successful save creates exact text then clean reopen',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'note-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'test.md');const s=api.createNoteSession();s.edit('# 測試\n<script>bad()</script>');await s.save({chooseSave:async()=>file});const reopened=api.createNoteSession();await reopened.open({chooseOpen:async()=>file});assert.equal(reopened.snapshot().text,s.snapshot().text);assert.equal(reopened.snapshot().dirty,false);assert.ok(api.previewBlocks(reopened.snapshot().text).every(b=>['h1','h2','h3','p','li'].includes(b.tag)));});
